static-site:
  nameOverride: chatup
  fullnameOverride: chatup
  domain: chatup.therobot.codes
  extraHosts: []
  image: ops.noizu.com/chatup.therobot.codes/web:sha-59c1361
  port: 80
  imagePullSecrets:
    - name: ops-registry-secret
  tls:
    secretName: chatup-therobot-codes-tls
    infisical:
      enabled: true
      secretsPath: "/apps/tls/chatuptherobotcodes"
      crtKey: CHATUP_TLS_CRT
      keyKey: CHATUP_TLS_KEY
